version: "3.8"

services:
  # Database container
  database:
    image: mysql
    container_name: mysql-container
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_DATABASE: SymfonyDB
    networks:
      - dev

  # Phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database
    networks:
      - dev

  # Maildev container
  maildev:
    image: maildev/maildev
    container_name: maildev-container
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "1500:80"
    restart: always
    networks:
      - dev

  # APACHE + PHP 8.0 container
  web:
    container_name: web-container
    build:
      context: ./docker/php
    ports:
      - "80:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./app/:/var/www/app:cached
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: